---
apiVersion: v1
kind: Service
metadata:
  name: python-example-service
  labels:
    run: python-example
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    run: python-example