apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-demo
  namespace: demo
spec:
  project: default
  source:
    repoURL: https://github.com/lvthao/cicd.git
    targetRevision: main
    path: docker/go/manifest/
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
