name: build_image

on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/python.yml
      - docker/python/**
    tags:        
      - '*'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: git_version
        run: pwd && ls -la && cat ./docker/python/version
      -
        name: Build and push image to docker 
        uses: docker/build-push-action@v3
        with:
          context: ./docker/python/
          file: ./docker/python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/python:$(cat ./docker/python/version)

